import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono"
import { cn } from "@repo/ui/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(GeistMono.className)}>{children}</body>
    </html>
  );
}
